Insert into [Equipa] VALUES('519', 'Alba Berlin', 'Germany', '40');
Insert into [Equipa] VALUES('520', 'Bamberg', 'Germany', '40');
Insert into [Equipa] VALUES('521', 'Basketball Braunschweig', 'Germany', '40');
Insert into [Equipa] VALUES('522', 'Bayern', 'Germany', '40');
Insert into [Equipa] VALUES('523', 'Bayreuth', 'Germany', '40');
Insert into [Equipa] VALUES('524', 'Bonn', 'Germany', '40');
Insert into [Equipa] VALUES('550', 'Chemnitz', 'Germany', '40');
Insert into [Equipa] VALUES('525', 'Crailsheim Merlins', 'Germany', '40');
Insert into [Equipa] VALUES('526', 'Frankfurt', 'Germany', '40');
Insert into [Equipa] VALUES('527', 'Giessen', 'Germany', '40');
Insert into [Equipa] VALUES('528', 'Gottingen', 'Germany', '40');
Insert into [Equipa] VALUES('529', 'Hamburg', 'Germany', '40');
Insert into [Equipa] VALUES('530', 'Ludwigsburg', 'Germany', '40');
Insert into [Equipa] VALUES('532', 'Oldenburg', 'Germany', '40');
Insert into [Equipa] VALUES('535', 's.Oliver Wurzburg', 'Germany', '40');
Insert into [Equipa] VALUES('2263', 'Syntainics MBC', 'Germany', '40');
Insert into [Equipa] VALUES('533', 'Ulm', 'Germany', '40');
Insert into [Equipa] VALUES('534', 'Vechta', 'Germany', '40');
