Insert into [Liga] VALUES('18', 'Liga A', 'Argentina');
Insert into [Liga] VALUES('1', 'NBL', 'Australia');
Insert into [Liga] VALUES('3', 'NBL W', 'Australia');
Insert into [Liga] VALUES('121', 'Austria Cup', 'Austria');
Insert into [Liga] VALUES('7', 'Zweite Liga', 'Austria');
Insert into [Liga] VALUES('122', 'Premier League', 'Bahrain');
Insert into [Liga] VALUES('111', 'Premier League', 'Belarus');
Insert into [Liga] VALUES('112', 'Premier League W', 'Belarus');
Insert into [Liga] VALUES('24', 'EuroMillions Basketball League', 'Belgium');
Insert into [Liga] VALUES('25', 'Top Division Women', 'Belgium');
Insert into [Liga] VALUES('123', 'Prvenstvo BiH', 'Bosnia-and-Herzegovina');
Insert into [Liga] VALUES('26', 'NBB', 'Brazil');
Insert into [Liga] VALUES('113', 'NBL', 'Bulgaria');
Insert into [Liga] VALUES('114', 'LNB', 'Chile');
Insert into [Liga] VALUES('31', 'CBA', 'China');
Insert into [Liga] VALUES('125', 'WCBA Women', 'China');
Insert into [Liga] VALUES('126', 'Croatian Cup', 'Croatia');
Insert into [Liga] VALUES('30', 'Premijer liga', 'Croatia');
Insert into [Liga] VALUES('115', 'Division A', 'Cyprus');
Insert into [Liga] VALUES('127', 'Czech Cup', 'Czech Republic');
Insert into [Liga] VALUES('128', 'Czech Cup Women', 'Czech Republic');
Insert into [Liga] VALUES('32', 'NBL', 'Czech Republic');
Insert into [Liga] VALUES('33', 'ZBL W', 'Czech Republic');
Insert into [Liga] VALUES('34', 'Basketligaen', 'Denmark');
Insert into [Liga] VALUES('35', 'Dameligaen W', 'Denmark');
Insert into [Liga] VALUES('129', 'Denmark Cup', 'Denmark');
Insert into [Liga] VALUES('130', 'Denmark Cup Women', 'Denmark');
Insert into [Liga] VALUES('36', 'Korvpalli Meistriliiga', 'Estonia');
Insert into [Liga] VALUES('37', 'Korisliiga', 'Finland');
Insert into [Liga] VALUES('38', 'Korisliiga W', 'Finland');
Insert into [Liga] VALUES('10', 'LFB W', 'France');
Insert into [Liga] VALUES('2', 'LNB', 'France');
Insert into [Liga] VALUES('8', 'Pro B', 'France');
Insert into [Liga] VALUES('39', 'Superleague', 'Georgia');
Insert into [Liga] VALUES('40', 'BBL', 'Germany');
Insert into [Liga] VALUES('41', 'DBBL Women', 'Germany');
Insert into [Liga] VALUES('134', 'German Cup', 'Germany');
Insert into [Liga] VALUES('42', 'Pro A', 'Germany');
Insert into [Liga] VALUES('43', 'Pro B', 'Germany');
Insert into [Liga] VALUES('44', 'A2', 'Greece');
Insert into [Liga] VALUES('45', 'Basket League', 'Greece');
Insert into [Liga] VALUES('136', 'Greek Cup', 'Greece');
Insert into [Liga] VALUES('137', 'Hungarian Cup Women', 'Hungary');
Insert into [Liga] VALUES('46', 'NB I A', 'Hungary');
Insert into [Liga] VALUES('47', 'NB I A W', 'Hungary');
Insert into [Liga] VALUES('48', 'Premier league', 'Iceland');
Insert into [Liga] VALUES('49', 'Premier League W', 'Iceland');
Insert into [Liga] VALUES('50', 'Super League', 'Ireland');
Insert into [Liga] VALUES('140', 'Israel Cup', 'Israel');
Insert into [Liga] VALUES('51', 'Super League', 'Israel');
Insert into [Liga] VALUES('52', 'Lega A', 'Italy');
Insert into [Liga] VALUES('53', 'Serie A1 W', 'Italy');
Insert into [Liga] VALUES('56', 'B League', 'Japan');
Insert into [Liga] VALUES('57', 'National League', 'Kazakhstan');
Insert into [Liga] VALUES('58', 'Premier League', 'Kazakhstan');
Insert into [Liga] VALUES('59', 'Superliga', 'Kosovo');
Insert into [Liga] VALUES('146', 'LBL', 'Latvia');
Insert into [Liga] VALUES('60', 'LKL', 'Lithuania');
Insert into [Liga] VALUES('62', 'Moteru Lyga W', 'Lithuania');
Insert into [Liga] VALUES('61', 'NKL', 'Lithuania');
Insert into [Liga] VALUES('150', 'Macedonian Cup', 'Macedonia');
Insert into [Liga] VALUES('67', 'Superleague', 'Macedonia');
Insert into [Liga] VALUES('63', 'LNBP', 'Mexico');
Insert into [Liga] VALUES('64', 'Prva A Liga', 'Montenegro');
Insert into [Liga] VALUES('65', 'DBL', 'Netherlands');
Insert into [Liga] VALUES('149', 'NBB Cup', 'Netherlands');
Insert into [Liga] VALUES('68', 'BLNO', 'Norway');
Insert into [Liga] VALUES('69', 'Kvinneligaen W', 'Norway');
Insert into [Liga] VALUES('151', 'Philippine Cup', 'Philippines');
Insert into [Liga] VALUES('71', '1 Liga', 'Poland');
Insert into [Liga] VALUES('72', 'Energa Basket Liga', 'Poland');
Insert into [Liga] VALUES('73', 'Energa Basket Liga W', 'Poland');
Insert into [Liga] VALUES('74', 'LPB', 'Portugal');
Insert into [Liga] VALUES('77', 'QBL', 'Qatar');
Insert into [Liga] VALUES('78', 'Divizia A', 'Romania');
Insert into [Liga] VALUES('79', 'Liga National W', 'Romania');
Insert into [Liga] VALUES('83', 'Premier League W', 'Russia');
Insert into [Liga] VALUES('159', 'Russian Cup', 'Russia');
Insert into [Liga] VALUES('81', 'Super League', 'Russia');
Insert into [Liga] VALUES('82', 'VTB United League', 'Russia');
Insert into [Liga] VALUES('84', 'Premier League', 'Saudi Arabia');
Insert into [Liga] VALUES('85', 'First League', 'Serbia');
Insert into [Liga] VALUES('87', 'Extraliga', 'Slovakia');
Insert into [Liga] VALUES('88', 'Extraliga W', 'Slovakia');
Insert into [Liga] VALUES('90', '1 SKL W', 'Slovenia');
Insert into [Liga] VALUES('89', 'Liga Nova KBM', 'Slovenia');
Insert into [Liga] VALUES('163', 'Slovenian Cup', 'Slovenia');
Insert into [Liga] VALUES('91', 'KBL', 'South Korea');
Insert into [Liga] VALUES('92', 'WKBL W', 'South Korea');
Insert into [Liga] VALUES('117', 'ACB', 'Spain');
Insert into [Liga] VALUES('95', 'LEB - Oro', 'Spain');
Insert into [Liga] VALUES('96', 'LEB - Plata', 'Spain');
Insert into [Liga] VALUES('94', 'Liga Femenina W', 'Spain');
Insert into [Liga] VALUES('98', 'Basketettan W', 'Sweden');
Insert into [Liga] VALUES('93', 'Basketligan', 'Sweden');
Insert into [Liga] VALUES('97', 'Basketligan W', 'Sweden');
Insert into [Liga] VALUES('99', 'Superettan', 'Sweden');
Insert into [Liga] VALUES('100', 'SB League', 'Switzerland');
Insert into [Liga] VALUES('101', 'SB League W', 'Switzerland');
Insert into [Liga] VALUES('170', 'Federation Cup', 'Turkey');
Insert into [Liga] VALUES('105', 'KBSL W', 'Turkey');
Insert into [Liga] VALUES('104', 'Super Ligi', 'Turkey');
Insert into [Liga] VALUES('103', 'TB2L', 'Turkey');
Insert into [Liga] VALUES('102', 'TBL', 'Turkey');
Insert into [Liga] VALUES('106', 'FBU Superleague', 'Ukraine');
Insert into [Liga] VALUES('107', 'Superleague W', 'Ukraine');
Insert into [Liga] VALUES('171', 'Ukrainian Cup', 'Ukraine');
Insert into [Liga] VALUES('108', 'BBL', 'United Kingdom');
Insert into [Liga] VALUES('174', 'BBL Cup', 'United Kingdom');
Insert into [Liga] VALUES('173', 'BBL Trophy', 'United Kingdom');
Insert into [Liga] VALUES('109', 'WBBL W', 'United Kingdom');
Insert into [Liga] VALUES('110', 'Liga Uruguaya', 'Uruguay');
Insert into [Liga] VALUES('12', 'NBA', 'USA');
Insert into [Liga] VALUES('20', 'NBA - G League', 'USA');
Insert into [Liga] VALUES('116', 'NCAA', 'USA');
