Insert into [Equipa] VALUES('120', 'Bourges W', 'France', '10');
Insert into [Equipa] VALUES('121', 'Charnay Bourgogne Sud W', 'France', '10');
Insert into [Equipa] VALUES('1802', 'ESB Villeneuve W', 'France', '10');
Insert into [Equipa] VALUES('123', 'Flammes Carolo W', 'France', '10');
Insert into [Equipa] VALUES('124', 'La Roche W', 'France', '10');
Insert into [Equipa] VALUES('125', 'Landerneau Bretagne W', 'France', '10');
Insert into [Equipa] VALUES('126', 'Landes W', 'France', '10');
Insert into [Equipa] VALUES('127', 'Lattes Montpellier W', 'France', '10');
Insert into [Equipa] VALUES('128', 'Lyon W', 'France', '10');
Insert into [Equipa] VALUES('129', 'Nantes W', 'France', '10');
Insert into [Equipa] VALUES('130', 'Tarbes GB W', 'France', '10');
Insert into [Equipa] VALUES('131', 'Union Hainaut W', 'France', '10');
