Insert into [Equipa] VALUES('1799', 'Academica', 'Portugal', '74');
Insert into [Equipa] VALUES('932', 'Barreirense', 'Portugal', '74');
Insert into [Equipa] VALUES('933', 'Benfica', 'Portugal', '74');
Insert into [Equipa] VALUES('934', 'CAB Madeira', 'Portugal', '74');
Insert into [Equipa] VALUES('935', 'Esgueira', 'Portugal', '74');
Insert into [Equipa] VALUES('936', 'FC Porto', 'Portugal', '74');
Insert into [Equipa] VALUES('937', 'Galitos', 'Portugal', '74');
Insert into [Equipa] VALUES('946', 'Imortal', 'Portugal', '74');
Insert into [Equipa] VALUES('939', 'Lusitania', 'Portugal', '74');
Insert into [Equipa] VALUES('940', 'Maia', 'Portugal', '74');
Insert into [Equipa] VALUES('941', 'Oliveirense', 'Portugal', '74');
Insert into [Equipa] VALUES('942', 'Ovarense', 'Portugal', '74');
Insert into [Equipa] VALUES('943', 'Sporting CP', 'Portugal', '74');
Insert into [Equipa] VALUES('945', 'Vitoria', 'Portugal', '74');
