Insert into [Equipa] VALUES('132', 'Atlanta Hawks', 'USA', '12');
Insert into [Equipa] VALUES('133', 'Boston Celtics', 'USA', '12');
Insert into [Equipa] VALUES('134', 'Brooklyn Nets', 'USA', '12');
Insert into [Equipa] VALUES('135', 'Charlotte Hornets', 'USA', '12');
Insert into [Equipa] VALUES('136', 'Chicago Bulls', 'USA', '12');
Insert into [Equipa] VALUES('137', 'Cleveland Cavaliers', 'USA', '12');
Insert into [Equipa] VALUES('138', 'Dallas Mavericks', 'USA', '12');
Insert into [Equipa] VALUES('139', 'Denver Nuggets', 'USA', '12');
Insert into [Equipa] VALUES('140', 'Detroit Pistons', 'USA', '12');
Insert into [Equipa] VALUES('141', 'Golden State Warriors', 'USA', '12');
Insert into [Equipa] VALUES('142', 'Houston Rockets', 'USA', '12');
Insert into [Equipa] VALUES('143', 'Indiana Pacers', 'USA', '12');
Insert into [Equipa] VALUES('144', 'Los Angeles Clippers', 'USA', '12');
Insert into [Equipa] VALUES('145', 'Los Angeles Lakers', 'USA', '12');
Insert into [Equipa] VALUES('146', 'Memphis Grizzlies', 'USA', '12');
Insert into [Equipa] VALUES('147', 'Miami Heat', 'USA', '12');
Insert into [Equipa] VALUES('148', 'Milwaukee Bucks', 'USA', '12');
Insert into [Equipa] VALUES('149', 'Minnesota Timberwolves', 'USA', '12');
Insert into [Equipa] VALUES('150', 'New Orleans Pelicans', 'USA', '12');
Insert into [Equipa] VALUES('151', 'New York Knicks', 'USA', '12');
Insert into [Equipa] VALUES('152', 'Oklahoma City Thunder', 'USA', '12');
Insert into [Equipa] VALUES('153', 'Orlando Magic', 'USA', '12');
Insert into [Equipa] VALUES('154', 'Philadelphia 76ers', 'USA', '12');
Insert into [Equipa] VALUES('155', 'Phoenix Suns', 'USA', '12');
Insert into [Equipa] VALUES('156', 'Portland Trail Blazers', 'USA', '12');
Insert into [Equipa] VALUES('157', 'Sacramento Kings', 'USA', '12');
Insert into [Equipa] VALUES('158', 'San Antonio Spurs', 'USA', '12');
Insert into [Equipa] VALUES('2511', 'Team Durant', 'USA', '12');
Insert into [Equipa] VALUES('1412', 'Team LeBron', 'USA', '12');
Insert into [Equipa] VALUES('159', 'Toronto Raptors', 'USA', '12');
Insert into [Equipa] VALUES('160', 'Utah Jazz', 'USA', '12');
Insert into [Equipa] VALUES('161', 'Washington Wizards', 'USA', '12');
